// modal Type
export const ModalType = {
  INCOME_SUBSCRIBE_COMPLETE: 'INCOME_SUBSCRIBE_COMPLETE',
  INCOME_ALARM_COMPLETE: 'INCOME_ALARM_COMPLETE',
  INCOME_APP_INSTALL: 'INCOME_APP_INSTALL',
  SHARE: 'SHARE',
  LOADING: 'LOADING'
}

export const DimmedType = {
  BLACK: 'BLACK',
  WHITE: 'WHITE'
}
