export { default as Home } from './home'
export { default as About } from './about'
export { default as Nav } from './nav'
export { default as Post } from './post'
export { default as Posts } from './posts'
export { default as ModalTestPage } from './modalTest'
